/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import controllers.BankConnection;
import controllers.DataStore;
import java.sql.*;
import java.util.logging.*;
import javax.swing.JOptionPane;

/**
 *
 * @author 63921
 */
public class UserLogin extends javax.swing.JFrame {

    /**
     * Creates new form UserLogin
     */
    
    private Connection conn;
    
    public UserLogin() {
        initComponents();
        setLocationRelativeTo(null);
        try {
            BankConnection connection = new BankConnection();
            conn = connection.getConnection();
        } catch (SQLException ex) {
            Logger.getLogger(AdminLogin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField_userAccountNumber = new javax.swing.JTextField();
        jPasswordField_pinNumber = new javax.swing.JPasswordField();
        jButton_loginUserAccount = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextField_userAccountNumber.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTextField_userAccountNumber.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_userAccountNumber.setToolTipText("Enter Account Number");
        jTextField_userAccountNumber.setPreferredSize(new java.awt.Dimension(200, 30));

        jPasswordField_pinNumber.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPasswordField_pinNumber.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPasswordField_pinNumber.setToolTipText("Enter Pin Number");
        jPasswordField_pinNumber.setPreferredSize(new java.awt.Dimension(200, 30));

        jButton_loginUserAccount.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton_loginUserAccount.setText("Submit");
        jButton_loginUserAccount.setPreferredSize(new java.awt.Dimension(200, 40));
        jButton_loginUserAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_loginUserAccountActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(106, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton_loginUserAccount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPasswordField_pinNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_userAccountNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(94, 94, 94))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(124, 124, 124)
                .addComponent(jTextField_userAccountNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPasswordField_pinNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addComponent(jButton_loginUserAccount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(95, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_loginUserAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_loginUserAccountActionPerformed
        // TODO add your handling code here:
        try {
            PreparedStatement ps;
            ResultSet rs;
            
            String userAccountNumber = jTextField_userAccountNumber.getText().trim();
            String pinNumber = jPasswordField_pinNumber.getText().trim();
            
            String query = "SELECT * FROM accounts WHERE account_number=? AND pin_number=?";
            ps = conn.prepareStatement(query);
            ps.setString(1, userAccountNumber);
            ps.setString(2, pinNumber);
            rs = ps.executeQuery();
            
            if(rs.next()){
                //event occur
                //System.out.println("Login Successful.");
                JOptionPane.showMessageDialog(null, "Login Successful.", "Login", JOptionPane.INFORMATION_MESSAGE);
                DataStore.getInstance().setStringData(userAccountNumber);
                UserMainDashboard main = new UserMainDashboard();
                main.setVisible(true);
                dispose();
            }
            else{
                //System.out.println("Invalid username or password.");
                JOptionPane.showMessageDialog(null, "Invalid username or password.", "Login", JOptionPane.ERROR_MESSAGE);
            }
            rs.close();
            ps.close();
            conn.close();
        } catch (SQLException ex) {
            Logger.getLogger(UserLogin.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jButton_loginUserAccountActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_loginUserAccount;
    private javax.swing.JPasswordField jPasswordField_pinNumber;
    private javax.swing.JTextField jTextField_userAccountNumber;
    // End of variables declaration//GEN-END:variables
}
